---
name: Lint Nix Config

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - name: Run flake check
        run: nix flake check --no-update-lock-file --print-build-logs
      - name: Evaluate NixOS hosts
        run: |
          nix eval --raw --no-update-lock-file .#nixosConfigurations.desktop.config.system.build.toplevel.drvPath
          nix eval --raw --no-update-lock-file .#nixosConfigurations.wsl.config.system.build.toplevel.drvPath
      - name: Verify clean checkout
        run: git diff --exit-code
